---
- hosts: 127.0.0.1
  connection: local
  vars_prompt:
      - name: email
        prompt: "Please enter your e-mail address"
        private: no
  roles:
      - vim
      - tmux
      - git
      - bash

