---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
      - var_file: "vars.yml"
  pre_tasks:
  roles:
      - prompts
      - bash
      - vim
      - tmux
      - git
      - docker

