---
- name: Install scdaemon
  become: yes
  apt:
      name: scdaemon
      state: present

- name: Install gpg config in bashrc
  template:
      src: 202-gpg.jj2
      dest: "{{ bashrc_dir }}/202-gpg"
- name: SSH support in gpg conf
  lineinfile:
      path: ~/.gnupg/gpg-agent.conf
      regexp: '^enable-ssh-support'
      line: 'enable-ssh-support'
- name: Add Keygrip to sshcontrol
  lineinfile:
      path: ~/.gnupg/sshcontrol
      regexp: '205226BEAB9EED76727A063DFD055D77584BA18F'
      line: "205226BEAB9EED76727A063DFD055D77584BA18F"
